language: python
python:
  - "2.7.3"
  - "2.7.8"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
script: 
  python tests/tests.py
