language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8.16
  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.10.3
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  coverage run --source=ttoolly manage.py test tests;

