language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.5
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  coverage run --source=ttoolly manage.py test tests;
