language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  coverage run --source=ttoolly manage.py test tests;
