language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.19
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.16
  - DJANGO_VERSION=2.0.9
  - DJANGO_VERSION=2.1.3
matrix:
  exclude:
    - python: "2.7"
      env: "DJANGO_VERSION=2.0.2"
install: 
  - pip install -U pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  coverage run --source=ttoolly manage.py test tests;
