language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.7
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  coverage run --source=ttoolly manage.py test tests;

