language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.8
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
after_script:
  coveralls
script: 
  if [[ $DJANGO_VERSION == "1.4.22" ]] || [[ $DJANGO_VERSION == "1.5.12" ]];
    then echo -e "\nfrom tests_for_project import *\n" >> tests/tests.py && coverage run --source=ttoolly manage.py test tests;
    else coverage run --source=ttoolly manage.py test tests;
  fi
